# Site settings | 网站设置
title: 二狗子
SEOTitle: 二狗子的博客 | liujinwakayakulie
header-img: img/home-bg-he.png
email: 352155132@qq.com
description: "二狗子的博客"
keyword: "二狗子, 二狗子的博客, iOS blog"
url: "http://liujinwakayakulie.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/liujinwakayakulie/liujinwakayakulie.github.io.git" #code repository | 代码仓库


# Sidebar settings | 侧边栏设置
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "随便说点装逼的话"
sidebar-avatar: /img/27217579.jpeg      # 头像





# SNS settings | 社交网络设置
facebook_username: 
github_username: liujinwakayakulie  #底部加星同样需要这个
zhihu_username: 
csdn_username: 
jianshu_username: d4167ee8eef2




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
# 转换时排除某些文件夹或文件。被排除的文件或文件夹的路径是相对于网站源码目录的，源码目录以外不受影响。
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

Regeneration: true    # 允许文件修改时自动重新生成网站。





# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Gitalk
gitalk:
  enable: true    # 是否开启Gitalk评论
  clientID: dc8c71d9f9e7b63751d7                            #生成的clientID
  clientSecret: 6a46833bd685a2e3f4fcbba80d3e2b7fb9ab0248    #生成的clientSecret
  repo: liujinwakayakulie.github.io    #仓库名称
  owner: liujinwakayakulie    # github用户名
  admin: liujinwakayakulie
  distractionFreeMode: true # 是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: ea7942bdce17d2e7ee9147028d5258b7

# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
# 右侧链接，我是个没有感情的杀手，所以也就没有写哈哈
# friends: [
#     {
#         title: "GitHub·RainbomSea",
#         href: "http://RainbomSea.github.io"
#     },{
#         title: "CSDN·RainbomSea",
#         href: "https://blog.csdn.net/qq_39268193"
#     },{
#         title: "知乎·RainbomSea",
#         href: "https://www.zhihu.com/people/RainbomSea"
#     },{
#         title: "GitBook·RainbomSea",
#         href: "https://legacy.gitbook.com/@rainbomsea"
#     }
# ]
